---
dependency:
  name: galaxy
  options:
    requirements-file: requirements.yml
driver:
  options:
    managed: false
    login_cmd_template: "podman exec -ti {instance} bash"
    ansible_connection_options:
      ansible_connection: podman
platforms:
  - name: fedora42
    image: registry.fedoraproject.org/fedora:42
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    pre_build_image: true
    groups:
      - fedora
  - name: rhel9
    image: registry.access.redhat.com/ubi9
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    pre_build_image: true
    groups:
      - rhel
  - name: rhel10
    image: registry.access.redhat.com/ubi10
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    pre_build_image: true
    groups:
      - rhel
  - name: ubuntu2404
    image: docker.io/library/ubuntu:24.04
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    pre_build_image: true
    groups:
      - ubuntu
provisioner:
  name: ansible
verifier:
  name: ansible
...
