---
- name: Run preparation actions
  hosts: all
  gather_facts: false
  tasks:
    - name: Install python3-cryptography package
      ansible.builtin.dnf:
        name: python3-cryptography
        state: present
