---
- name: Prepare Ubuntu hosts
  hosts: ubuntu
  gather_facts: false
  tasks:

    - name: Update apt cache
      ansible.builtin.raw: apt update

    - name: Install Python3
      ansible.builtin.raw: DEBIAN_FRONTEND=noninteractive apt-get -y install python3
      args:
        executable: /bin/bash

- name: Prepare Fedora hosts
  hosts: fedora
  gather_facts: false
  tasks:

    - name: Install Python3
      ansible.builtin.raw: dnf -y install python3 python3-libdnf5
      args:
        executable: /bin/bash

- name: Install cryptography
  hosts: all
  tasks:

    - name: Install python3-cryptography package
      ansible.builtin.package:
        name: python3-cryptography
        state: present
...
